/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-05-29 11:59:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/pc/Desktop/N20DCCN161_NGUYENVANTRUONG/.metadata/.plugins/org.eclipse.wst.server.core/tmp4/wtpwebapps/ManageStaffVinMart/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1677652621816L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang = \"en\" dir = \"ltr\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <title>Quản lý nhân viên cửa hàng VinMart</title>\r\n");
      out.write("      <style>\r\n");
      out.write("      body{\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    font-family:montserrat;\r\n");
      out.write("    background-image: linear-gradient(120deg,#2c9be4,#8b47a8);\r\n");
      out.write("    height: 100vh;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center{\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    top: 50%;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    transform: translate(-50%,-50%);\r\n");
      out.write("    width: 400px;\r\n");
      out.write("    background: white;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center h1{\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 0 0 20px 0;\r\n");
      out.write("    border-bottom:  1px solid silver;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center form {\r\n");
      out.write("    padding: 0 40px;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("form .txt-field{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    border-bottom: 2px solid #adadad;\r\n");
      out.write("    margin: 30px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".txt-field input{\r\n");
      out.write("    width:100%;\r\n");
      out.write("    padding: 0 5px;\r\n");
      out.write("    height: 40px;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    background: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".txt-field label{\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    top:50%;\r\n");
      out.write("    left:5px;\r\n");
      out.write("    color: #adadad;\r\n");
      out.write("    transform: translateY(-50%);\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    pointer-events: none;\r\n");
      out.write("    transition: .5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".txt-field span::before{\r\n");
      out.write("    content: '';\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 40px;\r\n");
      out.write("    left:0;\r\n");
      out.write("    width: 0%;\r\n");
      out.write("    height: 2px;\r\n");
      out.write("    background:#2691d9;\r\n");
      out.write("    transition: .5s;\r\n");
      out.write("}\r\n");
      out.write(".txt-field input:focus~label,\r\n");
      out.write(".txt-field input:valid~label{\r\n");
      out.write("    top:-5px;\r\n");
      out.write("    color:#2691d9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".txt-field input:focus~span::before,\r\n");
      out.write(".txt-field input:valid~span::before{\r\n");
      out.write("   width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pass{\r\n");
      out.write("    margin: -5px 0 20px 5px;\r\n");
      out.write("    color:#a6a6a6;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pass:hover{\r\n");
      out.write("    text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type = \"submit\"]{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    border: 1px solid;\r\n");
      out.write("    background: #2691d9;\r\n");
      out.write("    border-radius:25px;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    color: #e9f4fb;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type = \"submit\"]:hover{\r\n");
      out.write("    border-color: #2691d9;\r\n");
      out.write("    transition: .5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".signup_link{\r\n");
      out.write("    margin:30px 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    color: #666666;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".signup_link a{\r\n");
      out.write("    color: #2691d9;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".signup_link a:hover{\r\n");
      out.write("    text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("      	\r\n");
      out.write("      </style>\r\n");
      out.write("      \r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"center\">\r\n");
      out.write("            <h1>Login</h1>\r\n");
      out.write("            <form method = \"post\" action = \"home.html\">\r\n");
      out.write("                <div class=\"txt-field\">\r\n");
      out.write("                    <input type=\"text\"  name = \"user\" required>\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    <label >Tài khoản:</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"txt-field\">\r\n");
      out.write("                    <input type=\"password\" name = \"password\" required>\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    <label >Mật khẩu:</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <input type=\"submit\" name = \"login\" value = \"Login\">\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"signup_link\">\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                	<script>\r\n");
      out.write("				    // Lấy element chứa message\r\n");
      out.write("				    var messageDiv = document.getElementById(\"mess\");\r\n");
      out.write("				    // Nếu element tồn tại và có message\r\n");
      out.write("				    if (messageDiv != null && messageDiv.innerHTML.trim() != \"\") {\r\n");
      out.write("				        // Đóng message sau 5 giây\r\n");
      out.write("				        setTimeout(function() {\r\n");
      out.write("				            messageDiv.style.display = \"none\";\r\n");
      out.write("				        }, 2000); // thời gian đóng message (5 giây)\r\n");
      out.write("    					}\r\n");
      out.write("				</script>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(153,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status == 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  					<p  style = \"color: red\" id = \"mess\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("  					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
