/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-06-20 10:44:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/pc/Desktop/N20DCCN161_NGUYENVANTRUONG/.metadata/.plugins/org.eclipse.wst.server.core/tmp4/wtpwebapps/ManageStaffVinMart/WEB-INF/lib/jstl-impl.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1677652621816L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html dir=\"ltr\" lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/sweetalert2@11.0.18/dist/sweetalert2.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- sweetalert2 js -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11.0.18/dist/sweetalert2.all.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert@2/dist/sweetalert.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/sweetalert@2/dist/sweetalert.min.css\">\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <!-- Tell the browser to be responsive to screen width -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"keywords\"\r\n");
      out.write("        content=\"wrappixel, admin dashboard, html css dashboard, web dashboard, bootstrap 5 admin, bootstrap 5, css3 dashboard, bootstrap 5 dashboard, Nice lite admin bootstrap 5 dashboard, frontend, responsive bootstrap 5 admin template, Nice admin lite design, Nice admin lite dashboard bootstrap 5 dashboard template\">\r\n");
      out.write("    <meta name=\"description\"\r\n");
      out.write("        content=\"Nice Admin Lite is powerful and clean admin dashboard template, inpired from Bootstrap Framework\">\r\n");
      out.write("    <meta name=\"robots\" content=\"noindex,nofollow\">\r\n");
      out.write("    <title>Tài khoản nhân viên</title>\r\n");
      out.write("    <link rel=\"canonical\" href=\"https://www.wrappixel.com/templates/niceadmin-lite/\" />\r\n");
      out.write("    <!-- Favicon icon -->\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"resources2/assets/images/logo-vinmart-inkythuatso.png\">\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/assets/libs/chartist/dist/chartist.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/dist/css/style.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("		<style>\r\n");
      out.write(".modal {\r\n");
      out.write("	display: none; /* mặc định được ẩn đi */\r\n");
      out.write("	position: fixed; /* vị trí cố định */\r\n");
      out.write("	z-index: 1; /* Ưu tiên hiển thị trên cùng */\r\n");
      out.write("	padding-top: 100px;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	overflow: auto;\r\n");
      out.write("	background-color: rgb(0, 0, 0);\r\n");
      out.write("	background-color: rgba(0, 0, 0, 0.4);\r\n");
      out.write("	margin-left: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box {\r\n");
      out.write("	margin: 100px auto;\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("}\r\n");
      out.write(".alert-success {\r\n");
      out.write("  color: #155724;\r\n");
      out.write("  background-color: #d4edda;\r\n");
      out.write("  border-color: #c3e6cb;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".alert-danger {\r\n");
      out.write("  color: #721c24;\r\n");
      out.write("  background-color: #f8d7da;\r\n");
      out.write("  border-color: #f5c6cb;\r\n");
      out.write("}\r\n");
      out.write(" .table-responsive {\r\n");
      out.write("        overflow-y: auto;\r\n");
      out.write("        max-height: 300px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .table-responsive table {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .table-responsive thead th {\r\n");
      out.write("        position: sticky;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        background-color: white;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- Preloader - style you can find in spinners.css -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <div class=\"preloader\">\r\n");
      out.write("        <div class=\"lds-ripple\">\r\n");
      out.write("            <div class=\"lds-pos\"></div>\r\n");
      out.write("            <div class=\"lds-pos\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- Main wrapper - style you can find in pages.scss -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <div id=\"main-wrapper\" data-navbarbg=\"skin6\" data-theme=\"light\" data-layout=\"vertical\" data-sidebartype=\"full\"\r\n");
      out.write("        data-boxed-layout=\"full\">\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Topbar header - style you can find in pages.scss -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <header class=\"topbar\" data-navbarbg=\"skin6\">\r\n");
      out.write("            <nav class=\"navbar top-navbar navbar-expand-md navbar-light\">\r\n");
      out.write("                <div class=\"navbar-header\" data-logobg=\"skin5\">\r\n");
      out.write("                    <!-- This is for the sidebar toggle which is visible on mobile only -->\r\n");
      out.write("                    <a class=\"nav-toggler waves-effect waves-light d-block d-md-none\" href=\"javascript:void(0)\">\r\n");
      out.write("                        <i class=\"ti-menu ti-close\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- Logo -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <div class=\"navbar-brand\">\r\n");
      out.write("                        <a href=\"#\" class=\"logo\">\r\n");
      out.write("                            <!-- Logo icon -->\r\n");
      out.write("                            <b class=\"logo-icon\">\r\n");
      out.write("                                <!--You can put here icon as well // <i class=\"wi wi-sunset\"></i> //-->\r\n");
      out.write("                                <!-- Dark Logo icon -->\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/assets/images/logo-vinmart-inkythuatso.jpg\" alt=\"homepage\" class=\"dark-logo\" />\r\n");
      out.write("                                <!-- Light Logo icon -->\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/assets/images/logo-vinmart-inkythuatso.jpg\" alt=\"homepage\" class=\"light-logo\" />\r\n");
      out.write("                            </b>\r\n");
      out.write("                            <!--End Logo icon -->\r\n");
      out.write("                            <!-- Logo text -->\r\n");
      out.write("                            <!-- <span class=\"logo-text\">\r\n");
      out.write("                                dark Logo text\r\n");
      out.write("                                <img src=\"resources2/assets/images/logo-text.png\" alt=\"homepage\" class=\"dark-logo\" />\r\n");
      out.write("                                Light Logo text\r\n");
      out.write("                                <img src=\"resources2/assets/images/logo-light-text.png\" class=\"light-logo\" alt=\"homepage\" />\r\n");
      out.write("                            </span> -->\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- End Logo -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- Toggle which is visible on mobile only -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- End Logo -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <div class=\"navbar-collapse collapse\" id=\"navbarSupportedContent\" data-navbarbg=\"skin6\">\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- toggle and nav items -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <ul class=\"navbar-nav float-start me-auto\">\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- Search -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        \r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- Right side toggle and nav items -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <ul class=\"navbar-nav float-end\">\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- User profile and search -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <li class=\"nav-item dropdown\">\r\n");
      out.write("                            <a class=\"nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/assets/images/users/1.jpg\" alt=\"admin\" class=\"rounded-circle\" width=\"31\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                            \r\n");
      out.write("                            <ul class=\"dropdown-menu dropdown-menu-end user-dd animated\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                                 <a class=\"dropdown-item\" href=\"thongtincanhan.html\" ><i class=\"fa fa-info-circle\" style=\"font-size:14px\"></i>\r\n");
      out.write("                                    Thông tin cá nhân</a>\r\n");
      out.write("                                     <a class=\"dropdown-item\" href=\"doimatkhau.html\" ><i class='fa fa-unlock' style='font-size:14px'></i>\r\n");
      out.write("                                    Đổi mật khẩu</a>\r\n");
      out.write("                                <a class=\"dropdown-item\" href=\"home.html\" ><i class=\"fa fa-sign-out\" style=\"font-size:14px\"></i>\r\n");
      out.write("                                    Đăng xuất</a>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- User profile and search -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Topbar header -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Left Sidebar - style you can find in sidebar.scss  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <aside class=\"left-sidebar\" data-sidebarbg=\"skin5\">\r\n");
      out.write("            <!-- Sidebar scroll-->\r\n");
      out.write("            <div class=\"scroll-sidebar\">\r\n");
      out.write("                <!-- Sidebar navigation-->\r\n");
      out.write("                <nav class=\"sidebar-nav\">\r\n");
      out.write("                    <ul id=\"sidebarnav\">\r\n");
      out.write("                    <li class=\"sidebar-item\">\r\n");
      out.write("                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"homepage1.html\"\r\n");
      out.write("                                aria-expanded=\"false\">\r\n");
      out.write("                                <i class=\"fa fa-home\"></i>\r\n");
      out.write("                                <span class=\"hide-menu\">Trang chủ</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"sidebar-item\">\r\n");
      out.write("                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"manageaccount.html\"\r\n");
      out.write("                                aria-expanded=\"false\">\r\n");
      out.write("                              <i class=\"fa fa-user\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                <span class=\"hide-menu\">Quản lý tài khoản</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"sidebar-item\">\r\n");
      out.write("                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"pages-profile.html\"\r\n");
      out.write("                                aria-expanded=\"false\">\r\n");
      out.write("                                <i class=\"fa fa-id-card-o\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                <span class=\"hide-menu\">Quản lý nhân viên</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"sidebar-item\">\r\n");
      out.write("                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"form-basic.html\"\r\n");
      out.write("                                aria-expanded=\"false\">\r\n");
      out.write("                                <i class=\"mdi mdi-arrange-bring-forward\"></i>\r\n");
      out.write("                                <span class=\"hide-menu\">Quản lý bảng lương</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"sidebar-item\">\r\n");
      out.write("                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"table-basic.html\"\r\n");
      out.write("                                aria-expanded=\"false\">\r\n");
      out.write("                                <i class=\"mdi mdi-border-none\"></i>\r\n");
      out.write("                                <span class=\"hide-menu\">Quản lý hợp đồng lao động</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"sidebar-item\">\r\n");
      out.write("                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"thongbao.html\"\r\n");
      out.write("                                aria-expanded=\"false\">\r\n");
      out.write("                             <i class=\"mdi mdi-comment-processing\"></i>\r\n");
      out.write("                                <span class=\"hide-menu\">Quản lý thông báo</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li> \r\n");
      out.write("                            <li class=\"sidebar-item\">\r\n");
      out.write("                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"quanlylichlamviec.html\"\r\n");
      out.write("                                aria-expanded=\"false\">\r\n");
      out.write("                                  <i class=\"mdi mdi-table-large\"></i>\r\n");
      out.write("                                <span class=\"hide-menu\">Quản lý lịch làm việc</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"sidebar-item\">\r\n");
      out.write("                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"starter-kit.html\"\r\n");
      out.write("                                aria-expanded=\"false\">\r\n");
      out.write("                               <i class=\"mdi mdi-briefcase-check\"></i>\r\n");
      out.write("                                <span class=\"hide-menu\">Quản lý chấm công</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"sidebar-item\">\r\n");
      out.write("                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"thongtincanhan.html\"\r\n");
      out.write("                                aria-expanded=\"false\">\r\n");
      out.write("                                <i class=\"mdi mdi-information-outline\"></i>\r\n");
      out.write("                                <span class=\"hide-menu\">Thông tin cá nhân</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li> \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- End Sidebar navigation -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End Sidebar scroll-->\r\n");
      out.write("        </aside>\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Left Sidebar - style you can find in sidebar.scss  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Page wrapper  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <div class=\"page-wrapper\">\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- Bread crumb and right sidebar toggle -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <div class=\"page-breadcrumb\">\r\n");
      out.write("            <h4 class=\"page-title\" style = \"margin-left: 45%;\r\n");
      out.write("    font-size: 25px;\r\n");
      out.write("    color: orangered;\r\n");
      out.write("    font-family: FontAwesome\">Danh sách tài khoản</h4>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-5 align-self-center\">\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-7 align-self-center\">\r\n");
      out.write("                        <div class=\"d-flex align-items-center justify-content-end\">                          									\r\n");
      out.write("                        </div>                       \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("			</div>\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- End Bread crumb and right sidebar toggle -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- Container fluid  -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("						<span class=\"icon\"><i class=\"fa fa-search\"></i></span> <input onkeyup = \"searchTable('search','table-account')\"\r\n");
      out.write("							type=\"search\" id=\"search\" placeholder=\"Tìm kiếm thông tin nhân viên\" style = \"width:300px; margin-bottom: 10px\"/>\r\n");
      out.write("					\r\n");
      out.write("				<!--<p id = \"thongbaoloi\" style = \"color:red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>-->\r\n");
      out.write("		<script>\r\n");
      out.write("    var message = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mess}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("    if (message === \"Tài khoản đã cập nhật thành công\" || message === \"Tài khoản đã thêm thành công\" || message === \"Tài khoản đã reset mật khẩu thành công\") {\r\n");
      out.write("        swal({\r\n");
      out.write("            title: \"Thông báo\",\r\n");
      out.write("            text: message,\r\n");
      out.write("            icon: \"success\",\r\n");
      out.write("            button: \"OK\",\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    else if (message === \"Tài khoản đã tồn tại\" || message === \"Mã nhân viên chưa tạo\"){\r\n");
      out.write("    	 swal({\r\n");
      out.write("             title: \"Thông báo\",\r\n");
      out.write("             text: message,\r\n");
      out.write("             icon: \"error\",\r\n");
      out.write("             button: \"OK\",\r\n");
      out.write("         });\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("</script>\r\n");
      out.write("				<script>\r\n");
      out.write("				    // Lấy element chứa message\r\n");
      out.write("				    var messageDiv = document.getElementById(\"thongbaoloi\");\r\n");
      out.write("				    // Nếu element tồn tại và có message\r\n");
      out.write("				    if (messageDiv != null && messageDiv.innerHTML.trim() != \"\") {\r\n");
      out.write("				        // Đóng message sau 5 giây\r\n");
      out.write("				        setTimeout(function() {\r\n");
      out.write("				            messageDiv.style.display = \"none\";\r\n");
      out.write("				        }, 2000); // thời gian đóng message (5 giây)\r\n");
      out.write("    					}\r\n");
      out.write("				</script>\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Email campaign chart -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                \r\n");
      out.write("                      \r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Email campaign chart -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Ravenue - page-view-bounce rate -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <!-- column -->\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"table-responsive\">\r\n");
      out.write("								<table class=\"table table-hover\" id = \"table-account\">                        \r\n");
      out.write("                                    <thead>\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th class=\"border-top-0\">Tên tài khoản</th>                                            \r\n");
      out.write("                                            <th class=\"border-top-0\">Trạng thái</th>   \r\n");
      out.write("                                            <th></th>                                         \r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                    	");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>                                                              \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Ravenue - page-view-bounce rate -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Recent comment and chats -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("               <!--   <script>\r\n");
      out.write("  			window.onload = function() {\r\n");
      out.write("  		\r\n");
      out.write("    		document.getElementById(\"inform\").style.display = \"block\";\r\n");
      out.write("  			}\r\n");
      out.write("	</script>\r\n");
      out.write("	-->\r\n");
      out.write("               \r\n");
      out.write("            <script>\r\n");
      out.write("            document.querySelector(\".close\").addEventListener(\"click\", function() {\r\n");
      out.write("            	  document.getElementById(\"form-addcount\").reset();\r\n");
      out.write("            	});\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("</script>\r\n");
      out.write("                    <script>\r\n");
      out.write("                    var addEmployeeBtn = document.querySelector('#btnthemtk');\r\n");
      out.write("\r\n");
      out.write("                 // Thêm sự kiện click cho nút thêm nhân viên\r\n");
      out.write("                 addEmployeeBtn.addEventListener('click', function(event) {\r\n");
      out.write("                   event.preventDefault(); // Ngăn chặn mặc định hành vi chuyển hướng đến trang mới\r\n");
      out.write("\r\n");
      out.write("                   // Hiển thị modal\r\n");
      out.write("                   var modal = document.querySelector('#inform');\r\n");
      out.write("                   modal.style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("                   // Thay đổi URL\r\n");
      out.write("                   window.history.pushState(null, null, '#inform');\r\n");
      out.write("                 });\r\n");
      out.write("                    </script>\r\n");
      out.write("                    \r\n");
      out.write("                      <script>\r\n");
      out.write("                    var addEmployeeBtn = document.querySelector('#btnthemtk');\r\n");
      out.write("\r\n");
      out.write("                 // Thêm sự kiện click cho nút thêm nhân viên\r\n");
      out.write("                 addEmployeeBtn.addEventListener('click', function(event) {\r\n");
      out.write("                   event.preventDefault(); // Ngăn chặn mặc định hành vi chuyển hướng đến trang mới\r\n");
      out.write("\r\n");
      out.write("                   // Hiển thị modal\r\n");
      out.write("                   var modal = document.querySelector('#inform');\r\n");
      out.write("                   modal.style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("                   // Thay đổi URL\r\n");
      out.write("                   window.history.pushState(null, null, '#inform');\r\n");
      out.write("                 });\r\n");
      out.write("                    </script>\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Recent comment and chats -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"modal\" id = \"inform1\" onClick=\"stopCloseModal(event)\">\r\n");
      out.write("                    <!-- Column -->\r\n");
      out.write("                    <!-- Column -->\r\n");
      out.write("                    <!-- Column -->\r\n");
      out.write("                    <div class=\"col-lg-8 col-xlg-9\" style = \"margin-left: 200px\">\r\n");
      out.write("                        <div class=\"card\">\r\n");
      out.write("                            <div class=\"card-body\">\r\n");
      out.write("                                <form class=\"form-horizontal form-material mx-2\" action = \"manageaccount/add-account.html\"  method=\"POST\">                                    \r\n");
      out.write("                                   <span class=\"close\" style = \"float:right\">&times;</span>\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"col-md-12\">Tên tài khoản</label>\r\n");
      out.write("                                        <div class=\"col-md-12\">\r\n");
      out.write("                                            <input type=\"text\" name = \"id\" id = \"tentaikhoan\"\r\n");
      out.write("                                                class=\"form-control form-control-line\" readonly>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                  \r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"col-md-12\">Trạng thái</label>\r\n");
      out.write("                                        <div class=\"col-md-12\">\r\n");
      out.write("                                            <select class=\"form-select shadow-none form-control-line\"  name = \"status\" id = \"adc\">\r\n");
      out.write("                                                <option value = \"True\">Vẫn còn hoạt động</option>\r\n");
      out.write("                                                <option value = \"False\">Vô hiệu hóa</option>                                           \r\n");
      out.write("                                            </select>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                        <div class=\"col-sm-12\">                                         \r\n");
      out.write("                                            <button class=\"btn btn-success text-white\" type = \"submit\" name =\"btnupdate-account\">Cập nhật trạng thái</button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                   \r\n");
      out.write("                    <script>\r\n");
      out.write("    // lấy phần Modal\r\n");
      out.write(" var btn = document.querySelectorAll(\"button.modal-button\");\r\n");
      out.write("\r\n");
      out.write("// All page modals\r\n");
      out.write("var modals = document.querySelectorAll('.modal');\r\n");
      out.write("\r\n");
      out.write("// Get the <span> element that closes the modal\r\n");
      out.write("var spans = document.getElementsByClassName(\"close\");\r\n");
      out.write("\r\n");
      out.write("// When the user clicks the button, open the modal\r\n");
      out.write("for (var i = 0; i < btn.length; i++) {\r\n");
      out.write(" btn[i].onclick = function(e) {\r\n");
      out.write("    e.preventDefault();\r\n");
      out.write("    modal = document.querySelector(e.target.getAttribute(\"href\"));\r\n");
      out.write("    modal.style.display = \"block\";\r\n");
      out.write(" }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// When the user clicks on <span> (x), close the modal\r\n");
      out.write("for (var i = 0; i < spans.length; i++) {\r\n");
      out.write(" spans[i].onclick = function() {\r\n");
      out.write("    for (var index in modals) {\r\n");
      out.write("      if (typeof modals[index].style !== 'undefined') modals[index].style.display = \"none\";    \r\n");
      out.write("    }\r\n");
      out.write(" }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// When the user clicks anywhere outside of the modal, close it\r\n");
      out.write("window.onclick = function(event) {\r\n");
      out.write("    if (event.target.classList.contains('modal')) {\r\n");
      out.write("     for (var index in modals) {\r\n");
      out.write("      if (typeof modals[index].style !== 'undefined') modals[index].style.display = \"none\";    \r\n");
      out.write("     }\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function stopCloseModal(event) {\r\n");
      out.write("	  event.stopPropagation();\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<script>var updateButtons = document.querySelectorAll('.modal-button');\r\n");
      out.write("\r\n");
      out.write("		// Lặp qua từng nút và thêm sự kiện \"click\"\r\n");
      out.write("		updateButtons.forEach(function(button) {\r\n");
      out.write("		  button.addEventListener('click', function() {\r\n");
      out.write("		    // Lấy thông tin của nhân viên đang được chọn\r\n");
      out.write("		    var row = this.closest('tr');\r\n");
      out.write("		    var tentk = row.querySelector('td:nth-child(1)').innerText;\r\n");
      out.write("		    document.getElementById('tentaikhoan').value = tentk;\r\n");
      out.write("		    var trangthai = row.querySelector('td:nth-child(2)').innerText.trim();\r\n");
      out.write("		    if (trangthai === 'Vẫn còn hoạt động') {\r\n");
      out.write("		      document.getElementById('adc').value = 'True';\r\n");
      out.write("		    } else if (trangthai === 'Vô hiệu hóa') {\r\n");
      out.write("		      document.getElementById('adc').value = 'False';\r\n");
      out.write("		    }\r\n");
      out.write("		  });\r\n");
      out.write("		});</script>\r\n");
      out.write("     <!-- ============================================================== -->\r\n");
      out.write("                <!-- Recent comment and chats -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- End Container fluid  -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- footer -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <footer class=\"footer text-center\">\r\n");
      out.write("                All Rights Reserved by Nhóm 24. Designed and Developed by\r\n");
      out.write("                <a href=\"https://www.nhom24.com\">Nhom24</a>.\r\n");
      out.write("            </footer>\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- End footer -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Page wrapper  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- End Wrapper -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- All Jquery -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/assets/libs/jquery/dist/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap tether Core JavaScript -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <!-- slimscrollbar scrollbar JavaScript -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/assets/extra-libs/sparkline/sparkline.js\"></script>\r\n");
      out.write("    <!--Wave Effects -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/dist/js/waves.js\"></script>\r\n");
      out.write("    <!--Menu sidebar -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/dist/js/sidebarmenu.js\"></script>\r\n");
      out.write("    <!--Custom JavaScript -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/dist/js/custom.min.js\"></script>\r\n");
      out.write("    <script>function searchTable(inputId, tableId) {\r\n");
      out.write("		  let input = document.getElementById(inputId);\r\n");
      out.write("		  let table = document.getElementById(tableId);\r\n");
      out.write("		  let rows = table.getElementsByTagName(\"tr\");\r\n");
      out.write("		  input.addEventListener(\"keyup\", function () {\r\n");
      out.write("		    let value = input.value.toLowerCase();\r\n");
      out.write("		    for (let i = 1; i < rows.length; i++) {\r\n");
      out.write("		      let show = false;\r\n");
      out.write("		      let cells = rows[i].getElementsByTagName(\"td\");\r\n");
      out.write("		      for (let j = 0; j < cells.length; j++) {\r\n");
      out.write("		        let cell = cells[j];\r\n");
      out.write("		        if (cell.innerHTML.toLowerCase().indexOf(value) > -1) {\r\n");
      out.write("		          show = true;\r\n");
      out.write("		          break;\r\n");
      out.write("		        }\r\n");
      out.write("		      }\r\n");
      out.write("		      if (show) {\r\n");
      out.write("		        rows[i].style.display = \"\";\r\n");
      out.write("		      } else {\r\n");
      out.write("		        rows[i].style.display = \"none\";\r\n");
      out.write("		      }\r\n");
      out.write("		    }\r\n");
      out.write("		  });\r\n");
      out.write("		}</script>\r\n");
      out.write("    <!--This page JavaScript -->\r\n");
      out.write("    <!--chartis chart-->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/assets/libs/chartist/dist/chartist.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/assets/libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/dist/js/pages/dashboards/dashboard1.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/homepage.jsp(357,37) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("p");
      // /WEB-INF/views/homepage.jsp(357,37) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tk}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                        <tr>\r\n");
            out.write("                                            <td class=\"txt-oflo\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.nhanvien.maNV}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>                                                                                                                             \r\n");
            out.write("                                            <td class=\"txt-oflo\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${p.trangThaiHoatDong()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td> \r\n");
            out.write("                                            <td><button style=\"float: right\" id = \"btncapnhattk\" class= \"modal-button\" name = \"btncn\">\r\n");
            out.write("											<a href=\"#inform1\">Cập nhật tài khoản</a>\r\n");
            out.write("											</button> </td>                                                                                                                                                 	                                     \r\n");
            out.write("                                       	</tr>\r\n");
            out.write("                                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
