/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-06-20 03:44:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class trangchu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/pc/Desktop/N20DCCN161_NGUYENVANTRUONG/.metadata/.plugins/org.eclipse.wst.server.core/tmp4/wtpwebapps/ManageStaffVinMart/WEB-INF/lib/jstl-impl.jar!/META-INF/c.tld", Long.valueOf(1343794618000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-impl.jar", Long.valueOf(1677652621816L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html dir=\"ltr\" lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <!-- Tell the browser to be responsive to screen width -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"keywords\"\r\n");
      out.write("        content=\"wrappixel, admin dashboard, html css dashboard, web dashboard, bootstrap 5 admin, bootstrap 5, css3 dashboard, bootstrap 5 dashboard, Nice lite admin bootstrap 5 dashboard, frontend, responsive bootstrap 5 admin template, Nice admin lite design, Nice admin lite dashboard bootstrap 5 dashboard template\">\r\n");
      out.write("    <meta name=\"description\"\r\n");
      out.write("        content=\"Nice Admin Lite is powerful and clean admin dashboard template, inpired from Bootstrap Framework\">\r\n");
      out.write("    <meta name=\"robots\" content=\"noindex,nofollow\">\r\n");
      out.write("    <title>Trang chủ</title>\r\n");
      out.write("    <link rel=\"canonical\" href=\"https://www.wrappixel.com/templates/niceadmin-lite/\" />\r\n");
      out.write("    <!-- Favicon icon -->\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"resources2/assets/images/logo-vinmart-inkythuatso.png\">\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/assets/libs/chartist/dist/chartist.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Custom CSS -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/dist/css/style.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\"></script>\r\n");
      out.write("    <script src=\"https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("	<style>\r\n");
      out.write("		.table-responsive li:hover{\r\n");
      out.write("			background-color:yellow;\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- Preloader - style you can find in spinners.css -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <div class=\"preloader\">\r\n");
      out.write("        <div class=\"lds-ripple\">\r\n");
      out.write("            <div class=\"lds-pos\"></div>\r\n");
      out.write("            <div class=\"lds-pos\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- Main wrapper - style you can find in pages.scss -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <div id=\"main-wrapper\" data-navbarbg=\"skin6\" data-theme=\"light\" data-layout=\"vertical\" data-sidebartype=\"full\"\r\n");
      out.write("        data-boxed-layout=\"full\">\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Topbar header - style you can find in pages.scss -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <header class=\"topbar\" data-navbarbg=\"skin6\">\r\n");
      out.write("            <nav class=\"navbar top-navbar navbar-expand-md navbar-light\">\r\n");
      out.write("                <div class=\"navbar-header\" data-logobg=\"skin5\">\r\n");
      out.write("                    <!-- This is for the sidebar toggle which is visible on mobile only -->\r\n");
      out.write("                    <a class=\"nav-toggler waves-effect waves-light d-block d-md-none\" href=\"javascript:void(0)\">\r\n");
      out.write("                        <i class=\"ti-menu ti-close\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- Logo -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <div class=\"navbar-brand\">\r\n");
      out.write("                        <a href=\"#\" class=\"logo\">\r\n");
      out.write("                            <!-- Logo icon -->\r\n");
      out.write("                            <b class=\"logo-icon\">\r\n");
      out.write("                                <!--You can put here icon as well // <i class=\"wi wi-sunset\"></i> //-->\r\n");
      out.write("                                <!-- Dark Logo icon -->\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/assets/images/logo-vinmart-inkythuatso.jpg\" alt=\"homepage\" class=\"dark-logo\" />\r\n");
      out.write("                                <!-- Light Logo icon -->\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/assets/images/logo-vinmart-inkythuatso.jpg\" alt=\"homepage\" class=\"light-logo\" />\r\n");
      out.write("                            </b>\r\n");
      out.write("                            <!--End Logo icon -->\r\n");
      out.write("                            <!-- Logo text -->\r\n");
      out.write("                            <!-- <span class=\"logo-text\">\r\n");
      out.write("                                dark Logo text\r\n");
      out.write("                                <img src=\"resources2/assets/images/logo-text.png\" alt=\"homepage\" class=\"dark-logo\" />\r\n");
      out.write("                                Light Logo text\r\n");
      out.write("                                <img src=\"resources2/assets/images/logo-light-text.png\" class=\"light-logo\" alt=\"homepage\" />\r\n");
      out.write("                            </span> -->\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- End Logo -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- Toggle which is visible on mobile only -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- End Logo -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <div class=\"navbar-collapse collapse\" id=\"navbarSupportedContent\" data-navbarbg=\"skin6\">\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- toggle and nav items -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <ul class=\"navbar-nav float-start me-auto\">\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- Search -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <li class=\"nav-item search-box\">                          \r\n");
      out.write("                            <form class=\"app-search position-absolute\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" placeholder=\"Search &amp; enter\">\r\n");
      out.write("                                <a class=\"srh-btn\">\r\n");
      out.write("                                    <i class=\"ti-close\"></i>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <!-- Right side toggle and nav items -->\r\n");
      out.write("                    <!-- ============================================================== -->\r\n");
      out.write("                    <ul class=\"navbar-nav float-end\">\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- User profile and search -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <li class=\"nav-item dropdown\">\r\n");
      out.write("                            <a class=\"nav-link dropdown-toggle text-muted waves-effect waves-dark pro-pic\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/assets/images/users/1.jpg\" alt=\"admin\" class=\"rounded-circle\" width=\"31\">\r\n");
      out.write("                            </a>\r\n");
      out.write("                            \r\n");
      out.write("                            <ul class=\"dropdown-menu dropdown-menu-end user-dd animated\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                                 <a class=\"dropdown-item\" href=\"thongtincanhan.html\" ><i class=\"fa fa-info-circle\" style=\"font-size:14px\"></i>\r\n");
      out.write("                                    Thông tin cá nhân</a>\r\n");
      out.write("                                 <a class=\"dropdown-item\" href=\"changepassword.html\" ><i class='fa fa-unlock' style='font-size:14px'></i>\r\n");
      out.write("                                    Đổi mật khẩu</a>\r\n");
      out.write("                                <a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home.html\" ><i class=\"fa fa-sign-out\" style=\"font-size:14px\"></i>\r\n");
      out.write("                                    Đăng xuất</a>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                        <!-- User profile and search -->\r\n");
      out.write("                        <!-- ============================================================== -->\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Topbar header -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Left Sidebar - style you can find in sidebar.scss  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <aside class=\"left-sidebar\" data-sidebarbg=\"skin5\">\r\n");
      out.write("            <!-- Sidebar scroll-->\r\n");
      out.write("            <div class=\"scroll-sidebar\">\r\n");
      out.write("                <!-- Sidebar navigation-->\r\n");
      out.write("                <nav class=\"sidebar-nav\">\r\n");
      out.write("                    <ul id=\"sidebarnav\">\r\n");
      out.write("                    <li class=\"sidebar-item\">\r\n");
      out.write("                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"trangchu.html\"\r\n");
      out.write("                                aria-expanded=\"false\">\r\n");
      out.write("                               <i class=\"fa fa-home\"></i>\r\n");
      out.write("                                <span class=\"hide-menu\">Trang chủ</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>                                        \r\n");
      out.write("                        <li class=\"sidebar-item\">\r\n");
      out.write("                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"bangluong.html\"\r\n");
      out.write("                                aria-expanded=\"false\">\r\n");
      out.write("                                <i class=\"mdi mdi-arrange-bring-forward\"></i>\r\n");
      out.write("                                <span class=\"hide-menu\">Bảng lương</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"sidebar-item\">\r\n");
      out.write("                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"hopdonglaodong.html\"\r\n");
      out.write("                                aria-expanded=\"false\">\r\n");
      out.write("                                <i class=\"mdi mdi-border-none\"></i>\r\n");
      out.write("                                <span class=\"hide-menu\">Hợp đồng lao động</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"sidebar-item\">\r\n");
      out.write("                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"thongbao.html\"\r\n");
      out.write("                                aria-expanded=\"false\">\r\n");
      out.write("                                <i class=\"mdi mdi-comment-processing\"></i>\r\n");
      out.write("                                <span class=\"hide-menu\">Thông báo</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li> \r\n");
      out.write("                            <li class=\"sidebar-item\">\r\n");
      out.write("                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"lichlamviec.html\"\r\n");
      out.write("                                aria-expanded=\"false\">\r\n");
      out.write("                                  <i class=\"mdi mdi-table-large\"></i>\r\n");
      out.write("                                <span class=\"hide-menu\">Lịch làm việc</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"sidebar-item\">\r\n");
      out.write("                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"chamcong.html\"\r\n");
      out.write("                                aria-expanded=\"false\">\r\n");
      out.write("                                <i class=\"mdi mdi-briefcase-check\"></i>\r\n");
      out.write("                                <span class=\"hide-menu\">Chấm công</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                         <li class=\"sidebar-item\">\r\n");
      out.write("                            <a class=\"sidebar-link waves-effect waves-dark sidebar-link\" href=\"inform_staff.html\"\r\n");
      out.write("                                aria-expanded=\"false\">\r\n");
      out.write("                              <i class=\"mdi mdi-information-outline\"></i>\r\n");
      out.write("                                <span class=\"hide-menu\">Thông tin cá nhân</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- End Sidebar navigation -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End Sidebar scroll-->\r\n");
      out.write("        </aside>\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Left Sidebar - style you can find in sidebar.scss  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- Page wrapper  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <div class=\"page-wrapper\">\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- Bread crumb and right sidebar toggle -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <div class=\"page-breadcrumb\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-5 align-self-center\">\r\n");
      out.write("                        <h4 class=\"page-title\">Thông tin của nhóm 24</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-7 align-self-center\">\r\n");
      out.write("                        <div class=\"d-flex align-items-center justify-content-end\">\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- End Bread crumb and right sidebar toggle -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- Container fluid  -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <div class=\"container-fluid\">\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Email campaign chart -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                \r\n");
      out.write("                      \r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Email campaign chart -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Ravenue - page-view-bounce rate -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <!-- column -->\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <div class=\"card\">                   \r\n");
      out.write("                            <div class=\"table-responsive\">		\r\n");
      out.write("                             <ul>                          						\r\n");
      out.write("								<li><h1>Nguyễn Văn Trường - N20DCCN161</h1></li>\r\n");
      out.write("								<li><h1>Đậu Văn Hoàng - N20DCCN017</h1></li>\r\n");
      out.write("								<li><h1>Nguyễn Nhật Quang - N19DCPT055</h1></li>\r\n");
      out.write("								</ul>		\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Ravenue - page-view-bounce rate -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Recent comment and chats -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                \r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("                <!-- Recent comment and chats -->\r\n");
      out.write("                <!-- ============================================================== -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- End Container fluid  -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- footer -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <footer class=\"footer text-center\">\r\n");
      out.write("                All Rights Reserved by Nhóm 24. Designed and Developed by\r\n");
      out.write("                <a href=\"https://www.nhom24.com\">Nhom24</a>.\r\n");
      out.write("            </footer>\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("            <!-- End footer -->\r\n");
      out.write("            <!-- ============================================================== -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("        <!-- End Page wrapper  -->\r\n");
      out.write("        <!-- ============================================================== -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- End Wrapper -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <!-- All Jquery -->\r\n");
      out.write("    <!-- ============================================================== -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/assets/libs/jquery/dist/jquery.min.js\"></script>\r\n");
      out.write("    <!-- Bootstrap tether Core JavaScript -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <!-- slimscrollbar scrollbar JavaScript -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/assets/extra-libs/sparkline/sparkline.js\"></script>\r\n");
      out.write("    <!--Wave Effects -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/dist/js/waves.js\"></script>\r\n");
      out.write("    <!--Menu sidebar -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/dist/js/sidebarmenu.js\"></script>\r\n");
      out.write("    <!--Custom JavaScript -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/dist/js/custom.min.js\"></script>\r\n");
      out.write("    <!--This page JavaScript -->\r\n");
      out.write("    <!--chartis chart-->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/assets/libs/chartist/dist/chartist.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/assets/libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/resources2/dist/js/pages/dashboards/dashboard1.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
